In [1]:
import pandas as pd
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Embedding, GlobalAveragePooling1D, Dense, Dropout
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [2]:
x_train = np.load(r"../data/cleaned/x_train.npy")
x_test = np.load(r"../data/cleaned/x_test.npy")
x_val = np.load(r"../data/cleaned/x_val.npy")
y_train = np.load(r"../data/cleaned/y_train.npy")
y_test = np.load(r"../data/cleaned/y_test.npy")
y_val = np.load(r"../data/cleaned/y_val.npy")

In [3]:
x_train.shape,x_test.shape,x_val.shape

((34705, 200), (7438, 200), (7439, 200))

In [4]:
y_train.shape,y_test.shape,y_val.shape

((34705,), (7438,), (7439,))

In [5]:
x_train,x_test,x_val

(array([[    4,    15,    51, ...,     0,     0,     0],
        [    4,   150,  2060, ...,     0,     0,     0],
        [  488,    34,     2, ...,     0,     0,     0],
        ...,
        [  603,   100,  2577, ...,     0,     0,     0],
        [  662,  1001,   587, ...,     0,     0,     0],
        [ 1874, 14608,    44, ...,     0,     0,     0]],
       shape=(34705, 200), dtype=int32),
 array([[    5,    25,   493, ...,     0,     0,     0],
        [  258,   233,  5541, ...,     0,     0,     0],
        [  617,   573,     1, ...,     1,   937,   971],
        ...,
        [   78,  5617, 11034, ...,     0,     0,     0],
        [  149,   352,   637, ...,     0,     0,     0],
        [  209,     2,   265, ...,  4748,  6310,   209]],
       shape=(7438, 200), dtype=int32),
 array([[ 106,  315,    2, ...,    0,    0,    0],
        [   3,  415,  627, ...,    0,    0,    0],
        [2072,  337, 2918, ...,    0,    0,    0],
        ...,
        [ 122,  163,   68, ...,   12, 550

In [6]:
y_train,y_test,y_val

(array([0, 0, 0, ..., 0, 0, 1], shape=(34705,)),
 array([1, 0, 0, ..., 1, 1, 1], shape=(7438,)),
 array([1, 1, 0, ..., 1, 0, 0], shape=(7439,)))

In [ ]:
VOCAB_SIZE = 20000
MAX_LEN = 200

In [ ]:
#embediing dimension

In [8]:
ann_model_em100 = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=100
    ),
    GlobalAveragePooling1D(),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

In [9]:
ann_model_em100.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [10]:
history = ann_model_em100.fit(x_train,y_train, validation_data=(x_val,y_val),epochs=10,batch_size=32)

Epoch 1/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 30s 26ms/step - accuracy: 0.7973 - loss: 0.4250 - val_accuracy: 0.8687 - val_loss: 0.3071
Epoch 2/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 27s 25ms/step - accuracy: 0.9008 - loss: 0.2513 - val_accuracy: 0.8511 - val_loss: 0.3528
Epoch 3/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 26s 24ms/step - accuracy: 0.9242 - loss: 0.1983 - val_accuracy: 0.8839 - val_loss: 0.3005
Epoch 4/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 29s 27ms/step - accuracy: 0.9360 - loss: 0.1715 - val_accuracy: 0.8645 - val_loss: 0.3397
Epoch 5/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 30s 27ms/step - accuracy: 0.9492 - loss: 0.1416 - val_accuracy: 0.8912 - val_loss: 0.3085
Epoch 6/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 29s 27ms/step - accuracy: 0.9536 - loss: 0.1256 - val_accuracy: 0.8895 - val_loss: 0.3513
Epoch 7/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 30s 27ms/step - accuracy: 0.9585 - loss: 0.1154 - val_accuracy: 0.8801 - val_loss: 0.4029
Epoch 8/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 30s 28ms/step - accuracy: 0.9618 -

In [12]:
y_pred = ann_model_em100.predict(x_val)

233/233 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [13]:
y_pred = (y_pred >= 0.5).astype(int).ravel()
accuracy_ann = accuracy_score(y_val, y_pred)
precision_ann = precision_score(y_val, y_pred)
recall_ann = recall_score(y_val, y_pred)
f1_ann = f1_score(y_val, y_pred)
auc_score = roc_auc_score(y_val, y_pred)

print("Accuracy :", accuracy_ann)
print("Precision:", precision_ann)
print("Recall   :", recall_ann)
print("F1 Score :", f1_ann)
print("auc_score :",auc_score)

Accuracy : 0.8826455168705472
Precision: 0.8877440347071583
Recall   : 0.8770425930886686
F1 Score : 0.8823608678075731
auc_score : 0.8826659268735302


In [ ]:
#50

In [15]:
ann_model_em50 = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=50
    ),
    GlobalAveragePooling1D(),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

In [16]:
ann_model_em50.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [17]:
history = ann_model_em50.fit(x_train,y_train, validation_data=(x_val,y_val),epochs=10,batch_size=32)

Epoch 1/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 14s 12ms/step - accuracy: 0.7822 - loss: 0.4515 - val_accuracy: 0.8231 - val_loss: 0.3898
Epoch 2/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.8990 - loss: 0.2553 - val_accuracy: 0.8894 - val_loss: 0.2727
Epoch 3/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.9208 - loss: 0.2062 - val_accuracy: 0.8648 - val_loss: 0.3363
Epoch 4/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.9336 - loss: 0.1776 - val_accuracy: 0.8929 - val_loss: 0.2876
Epoch 5/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.9453 - loss: 0.1514 - val_accuracy: 0.8707 - val_loss: 0.3420
Epoch 6/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.9489 - loss: 0.1417 - val_accuracy: 0.8532 - val_loss: 0.4176
Epoch 7/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 12s 11ms/step - accuracy: 0.9588 - loss: 0.1173 - val_accuracy: 0.8895 - val_loss: 0.3521
Epoch 8/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.9631 -

In [19]:
y_pred = ann_model_em50.predict(x_val)
y_pred = (y_pred >= 0.5).astype(int).ravel()

233/233 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step


In [20]:
accuracy_ann = accuracy_score(y_val, y_pred)
precision_ann = precision_score(y_val, y_pred)
recall_ann = recall_score(y_val, y_pred)
f1_ann = f1_score(y_val, y_pred)
auc_score = roc_auc_score(y_val, y_pred)

print("Accuracy :", accuracy_ann)
print("Precision:", precision_ann)
print("Recall   :", recall_ann)
print("F1 Score :", f1_ann)
print("auc_score :",auc_score)

Accuracy : 0.8717569565801855
Precision: 0.8448746587242492
Recall   : 0.9118671309938388
F1 Score : 0.8770935325946921
auc_score : 0.8716108455832658


In [ ]:
#128

In [21]:
ann_model_em128 = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=128
    ),
    GlobalAveragePooling1D(),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

In [22]:
ann_model_em128.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
history = ann_model_em128.fit(x_train,y_train, validation_data=(x_val,y_val),epochs=10,batch_size=32)

Epoch 1/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 40s 36ms/step - accuracy: 0.7962 - loss: 0.4206 - val_accuracy: 0.8759 - val_loss: 0.2957
Epoch 2/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 41s 38ms/step - accuracy: 0.9011 - loss: 0.2473 - val_accuracy: 0.8864 - val_loss: 0.2783
Epoch 3/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 39s 36ms/step - accuracy: 0.9213 - loss: 0.2046 - val_accuracy: 0.8136 - val_loss: 0.4874
Epoch 4/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 38s 35ms/step - accuracy: 0.9345 - loss: 0.1740 - val_accuracy: 0.8867 - val_loss: 0.2982
Epoch 5/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 39s 36ms/step - accuracy: 0.9457 - loss: 0.1478 - val_accuracy: 0.8437 - val_loss: 0.4601
Epoch 6/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 38s 35ms/step - accuracy: 0.9508 - loss: 0.1304 - val_accuracy: 0.8595 - val_loss: 0.4329
Epoch 7/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 39s 36ms/step - accuracy: 0.9553 - loss: 0.1203 - val_accuracy: 0.8816 - val_loss: 0.3841
Epoch 8/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 39s 36ms/step - accuracy: 0.9627 -

In [23]:
y_pred = ann_model_em128.predict(x_val)
y_pred = (y_pred >= 0.5).astype(int).ravel()

233/233 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


In [24]:
accuracy_ann = accuracy_score(y_val, y_pred)
precision_ann = precision_score(y_val, y_pred)
recall_ann = recall_score(y_val, y_pred)
f1_ann = f1_score(y_val, y_pred)
auc_score = roc_auc_score(y_val, y_pred)

print("Accuracy :", accuracy_ann)
print("Precision:", precision_ann)
print("Recall   :", recall_ann)
print("F1 Score :", f1_ann)
print("auc_score :",auc_score)

Accuracy : 0.8786127167630058
Precision: 0.9033637400228051
Recall   : 0.8489150817037235
F1 Score : 0.8752934677530728
auc_score : 0.8787208975706962
