In [57]:
import pandas as pd
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Embedding, GlobalAveragePooling1D, Dense, Dropout, SimpleRNN, LSTM, GRU, Bidirectional
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [3]:
x_train = np.load(r"../data/cleaned/x_train.npy")
x_test = np.load(r"../data/cleaned/x_test.npy")
x_val = np.load(r"../data/cleaned/x_val.npy")
y_train = np.load(r"../data/cleaned/y_train.npy")
y_test = np.load(r"../data/cleaned/y_test.npy")
y_val = np.load(r"../data/cleaned/y_val.npy")

In [4]:
x_train.shape,x_test.shape,x_val.shape

((34705, 200), (7438, 200), (7439, 200))

In [5]:
y_train.shape,y_test.shape,y_val.shape

((34705,), (7438,), (7439,))

In [7]:
x_train,x_test,x_val

(array([[    4,    15,    51, ...,     0,     0,     0],
        [    4,   150,  2060, ...,     0,     0,     0],
        [  488,    34,     2, ...,     0,     0,     0],
        ...,
        [  603,   100,  2577, ...,     0,     0,     0],
        [  662,  1001,   587, ...,     0,     0,     0],
        [ 1874, 14608,    44, ...,     0,     0,     0]],
       shape=(34705, 200), dtype=int32),
 array([[    5,    25,   493, ...,     0,     0,     0],
        [  258,   233,  5541, ...,     0,     0,     0],
        [  617,   573,     1, ...,     1,   937,   971],
        ...,
        [   78,  5617, 11034, ...,     0,     0,     0],
        [  149,   352,   637, ...,     0,     0,     0],
        [  209,     2,   265, ...,  4748,  6310,   209]],
       shape=(7438, 200), dtype=int32),
 array([[ 106,  315,    2, ...,    0,    0,    0],
        [   3,  415,  627, ...,    0,    0,    0],
        [2072,  337, 2918, ...,    0,    0,    0],
        ...,
        [ 122,  163,   68, ...,   12, 550

In [8]:
y_train,y_test,y_val

(array([0, 0, 0, ..., 0, 0, 1], shape=(34705,)),
 array([1, 0, 0, ..., 1, 1, 1], shape=(7438,)),
 array([1, 1, 0, ..., 1, 0, 0], shape=(7439,)))

In [9]:
VOCAB_SIZE = 20000
MAX_LEN = 200
EMBEDDING_DIM = 100

In [ ]:
#basic ann model

In [11]:
ann_model = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),
    GlobalAveragePooling1D(),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

In [12]:
ann_model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
ann_model.fit(x_train,y_train, validation_data=(x_val,y_val),epochs=10,batch_size=32)

Epoch 1/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 29s 26ms/step - accuracy: 0.7897 - loss: 0.4345 - val_accuracy: 0.8301 - val_loss: 0.3706
Epoch 2/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 26s 24ms/step - accuracy: 0.8984 - loss: 0.2536 - val_accuracy: 0.8693 - val_loss: 0.3129
Epoch 3/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 29s 27ms/step - accuracy: 0.9192 - loss: 0.2093 - val_accuracy: 0.8941 - val_loss: 0.2742
Epoch 4/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 28s 26ms/step - accuracy: 0.9363 - loss: 0.1712 - val_accuracy: 0.8942 - val_loss: 0.2908
Epoch 5/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 29s 27ms/step - accuracy: 0.9463 - loss: 0.1474 - val_accuracy: 0.8622 - val_loss: 0.3925
Epoch 6/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 29s 27ms/step - accuracy: 0.9514 - loss: 0.1346 - val_accuracy: 0.8910 - val_loss: 0.3299
Epoch 7/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 29s 27ms/step - accuracy: 0.9611 - loss: 0.1098 - val_accuracy: 0.8790 - val_loss: 0.4074
Epoch 8/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 29s 27ms/step - accuracy: 0.9576 -

In [15]:
y_pred = ann_model.predict(x_val)

233/233 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [17]:
y_pred = (y_pred >= 0.5).astype(int).ravel()

In [ ]:
accuracy_ann = accuracy_score(y_val, y_pred)
precision_ann = precision_score(y_val, y_pred)
recall_ann = recall_score(y_val, y_pred)
f1_ann = f1_score(y_val, y_pred)
auc_score = roc_auc_score(y_val, y_pred)

print("Accuracy :", accuracy_ann)
print("Precision:", precision_ann)
print("Recall   :", recall_ann)
print("F1 Score :", f1_ann)
print("auc_score :",auc_score)

Accuracy : 0.8759241833579782
Precision: 0.8507239141288068
Recall   : 0.9129386552370747
F1 Score : 0.8807339449541285
auc_score : 0.8757893492051537


In [66]:
ann_model.save(r"../model/base_ann.keras")

In [23]:
baseline_performance = {"MODEL":[],
                        "ACCURACY":[],
                        "PRECISION":[],
                        "RECALL":[],
                        "F1 SCORE":[],
                        "AUC":[]}

In [24]:
def performance(name,acc,precision,recall,f1,auc):
    baseline_performance["MODEL"].append(name),
    baseline_performance["ACCURACY"].append(acc),
    baseline_performance["PRECISION"].append(precision),
    baseline_performance["RECALL"].append(recall),
    baseline_performance["F1 SCORE"].append(f1),
    baseline_performance["AUC"].append(auc)

In [25]:
performance("ANN",0.87,0.85,0.91,0.88,0.87)

In [ ]:
#rnn

In [29]:
rnn_model = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),
    SimpleRNN(64),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

In [30]:
rnn_model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [31]:
history = rnn_model.fit(x_train,y_train, validation_data=(x_val,y_val),epochs=10,batch_size=32)

Epoch 1/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 46s 40ms/step - accuracy: 0.4982 - loss: 0.6957 - val_accuracy: 0.5018 - val_loss: 0.6931
Epoch 2/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 42s 39ms/step - accuracy: 0.5028 - loss: 0.6932 - val_accuracy: 0.5096 - val_loss: 0.6931
Epoch 3/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 43s 39ms/step - accuracy: 0.5136 - loss: 0.6936 - val_accuracy: 0.5053 - val_loss: 0.6946
Epoch 4/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 44s 40ms/step - accuracy: 0.5527 - loss: 0.6418 - val_accuracy: 0.5050 - val_loss: 0.7246
Epoch 5/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 44s 40ms/step - accuracy: 0.5761 - loss: 0.5957 - val_accuracy: 0.5002 - val_loss: 0.8299
Epoch 6/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 43s 40ms/step - accuracy: 0.5776 - loss: 0.5905 - val_accuracy: 0.5044 - val_loss: 0.9350
Epoch 7/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 43s 40ms/step - accuracy: 0.5767 - loss: 0.5877 - val_accuracy: 0.5067 - val_loss: 1.0327
Epoch 8/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 44s 40ms/step - accuracy: 0.5765 -

In [32]:
y_pred = rnn_model.predict(x_val)

233/233 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step


In [33]:
y_pred = (y_pred >= 0.5).astype(int).ravel()

In [34]:
accuracy_rnn = accuracy_score(y_val, y_pred)
precision_rnn = precision_score(y_val, y_pred)
recall_rnn = recall_score(y_val, y_pred)
f1_rnn = f1_score(y_val, y_pred)
auc_score_rnn = roc_auc_score(y_val, y_pred)

print("Accuracy :", accuracy_rnn)
print("Precision:", precision_rnn)
print("Recall   :", recall_rnn)
print("F1 Score :", f1_rnn)
print("auc_score :",auc_score_rnn)

Accuracy : 0.5176771071380561
Precision: 0.5429248075784487
Recall   : 0.24564693276185373
F1 Score : 0.33825156768720027
auc_score : 0.518668042743582


In [35]:
performance("RNN",0.51,0.54,0.24,0.33,0.51)

In [67]:
rnn_model.save(r"../model/base_rnn.keras")

In [ ]:
#LSTM

In [38]:
lstm_model = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),
    LSTM(64),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

In [39]:
lstm_model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [40]:
lstm_model.fit(x_train,y_train, validation_data=(x_val,y_val),epochs=10,batch_size=32)

Epoch 1/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 69s 62ms/step - accuracy: 0.5132 - loss: 0.6928 - val_accuracy: 0.5284 - val_loss: 0.6852
Epoch 2/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 69s 64ms/step - accuracy: 0.5606 - loss: 0.6673 - val_accuracy: 0.5343 - val_loss: 0.6815
Epoch 3/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 69s 64ms/step - accuracy: 0.7707 - loss: 0.4715 - val_accuracy: 0.8212 - val_loss: 0.4323
Epoch 4/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 69s 64ms/step - accuracy: 0.8883 - loss: 0.2900 - val_accuracy: 0.8710 - val_loss: 0.3161
Epoch 5/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 69s 63ms/step - accuracy: 0.9290 - loss: 0.1930 - val_accuracy: 0.8798 - val_loss: 0.3169
Epoch 6/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 69s 63ms/step - accuracy: 0.9561 - loss: 0.1285 - val_accuracy: 0.8774 - val_loss: 0.3549
Epoch 7/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 68s 63ms/step - accuracy: 0.9762 - loss: 0.0808 - val_accuracy: 0.8758 - val_loss: 0.4464
Epoch 8/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 69s 63ms/step - accuracy: 0.9852 -

In [41]:
y_pred = lstm_model.predict(x_val)

233/233 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step


In [42]:
y_pred = (y_pred >= 0.5).astype(int).ravel()

In [43]:
accuracy_lstm = accuracy_score(y_val, y_pred)
precision_lstm = precision_score(y_val, y_pred)
recall_lstm = recall_score(y_val, y_pred)
f1_lstm = f1_score(y_val, y_pred)
auc_score_lstm = roc_auc_score(y_val, y_pred)

print("Accuracy :", accuracy_lstm)
print("Precision:", precision_lstm)
print("Recall   :", recall_lstm)
print("F1 Score :", f1_lstm)
print("auc_score :",auc_score_lstm)

Accuracy : 0.870143836537169
Precision: 0.8523045581869111
Recall   : 0.8965979105277256
F1 Score : 0.8738903394255875
auc_score : 0.8700474711839923


In [44]:
performance("LSTM",0.87,0.85,0.89,0.87,0.87)

In [45]:
baseline_performance

{'MODEL': ['ANN', 'RNN', 'LSTM'],
 'ACCURACY': [0.87, 0.51, 0.87],
 'PRECISION': [0.85, 0.54, 0.85],
 'RECALL': [0.91, 0.24, 0.89],
 'F1 SCORE': [0.88, 0.33, 0.87],
 'AUC': [0.87, 0.51, 0.87]}

In [68]:
lstm_model.save(r"../model/base_lstm.keras")

In [ ]:
#GRU

In [47]:
gru_model = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),
    GRU(64),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

In [48]:
gru_model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [49]:
gru_model.fit(x_train,y_train, validation_data=(x_val,y_val),epochs=10,batch_size=32)

Epoch 1/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 75s 67ms/step - accuracy: 0.5061 - loss: 0.6928 - val_accuracy: 0.5107 - val_loss: 0.6881
Epoch 2/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 74s 68ms/step - accuracy: 0.7811 - loss: 0.4336 - val_accuracy: 0.8839 - val_loss: 0.2797
Epoch 3/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 73s 67ms/step - accuracy: 0.9364 - loss: 0.1787 - val_accuracy: 0.8888 - val_loss: 0.2875
Epoch 4/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 73s 68ms/step - accuracy: 0.9731 - loss: 0.0845 - val_accuracy: 0.8739 - val_loss: 0.4002
Epoch 5/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 73s 68ms/step - accuracy: 0.9891 - loss: 0.0381 - val_accuracy: 0.8769 - val_loss: 0.5172
Epoch 6/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 73s 67ms/step - accuracy: 0.9949 - loss: 0.0184 - val_accuracy: 0.8766 - val_loss: 0.5431
Epoch 7/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 73s 68ms/step - accuracy: 0.9969 - loss: 0.0100 - val_accuracy: 0.8742 - val_loss: 0.8320
Epoch 8/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 73s 68ms/step - accuracy: 0.9980 -

In [52]:
y_pred = gru_model.predict(x_val)
y_pred = (y_pred >= 0.5).astype(int).ravel()

233/233 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step


In [53]:
accuracy_gru = accuracy_score(y_val, y_pred)
precision_gru = precision_score(y_val, y_pred)
recall_gru = recall_score(y_val, y_pred)
f1_gru = f1_score(y_val, y_pred)
auc_score_gru = roc_auc_score(y_val, y_pred)

print("Accuracy :", accuracy_gru)
print("Precision:", precision_gru)
print("Recall   :", recall_gru)
print("F1 Score :", f1_gru)
print("auc_score :",auc_score_gru)

Accuracy : 0.8792848501142627
Precision: 0.8719496195224351
Recall   : 0.8901687650683097
F1 Score : 0.880965005302227
auc_score : 0.8792452028255742


In [54]:
performance("GRU",0.87,0.87,0.89,0.88,0.87)

In [55]:
baseline_performance

{'MODEL': ['ANN', 'RNN', 'LSTM', 'GRU'],
 'ACCURACY': [0.87, 0.51, 0.87, 0.87],
 'PRECISION': [0.85, 0.54, 0.85, 0.87],
 'RECALL': [0.91, 0.24, 0.89, 0.89],
 'F1 SCORE': [0.88, 0.33, 0.87, 0.88],
 'AUC': [0.87, 0.51, 0.87, 0.87]}

In [69]:
gru_model.save(r"../model/base_gru.keras")

In [ ]:
#BILSTM

In [58]:
Bilstm_model = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),
    Bidirectional(LSTM(64)),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

In [59]:
Bilstm_model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [60]:
Bilstm_model.fit(x_train,y_train, validation_data=(x_val,y_val),epochs=10,batch_size=32)

Epoch 1/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 88s 77ms/step - accuracy: 0.8354 - loss: 0.3773 - val_accuracy: 0.8812 - val_loss: 0.2925
Epoch 2/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 83s 77ms/step - accuracy: 0.9213 - loss: 0.2122 - val_accuracy: 0.8792 - val_loss: 0.3070
Epoch 3/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 83s 77ms/step - accuracy: 0.9502 - loss: 0.1386 - val_accuracy: 0.8833 - val_loss: 0.3375
Epoch 4/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 83s 77ms/step - accuracy: 0.9665 - loss: 0.0969 - val_accuracy: 0.8540 - val_loss: 0.5052
Epoch 5/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 84s 77ms/step - accuracy: 0.9801 - loss: 0.0608 - val_accuracy: 0.8747 - val_loss: 0.5092
Epoch 6/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 84s 77ms/step - accuracy: 0.9865 - loss: 0.0429 - val_accuracy: 0.8661 - val_loss: 0.5488
Epoch 7/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 86s 79ms/step - accuracy: 0.9932 - loss: 0.0237 - val_accuracy: 0.8671 - val_loss: 0.6308
Epoch 8/10
1085/1085 ━━━━━━━━━━━━━━━━━━━━ 86s 79ms/step - accuracy: 0.9925 -

In [61]:
y_pred = Bilstm_model.predict(x_val)
y_pred = (y_pred >= 0.5).astype(int).ravel()

233/233 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step


In [62]:
accuracy_Bilstm = accuracy_score(y_val, y_pred)
precision_Bilstm = precision_score(y_val, y_pred)
recall_Bilstm = recall_score(y_val, y_pred)
f1_Bilstm = f1_score(y_val, y_pred)
auc_score_Bilstm = roc_auc_score(y_val, y_pred)

print("Accuracy :", accuracy_Bilstm)
print("Precision:", precision_Bilstm)
print("Recall   :", recall_Bilstm)
print("F1 Score :", f1_Bilstm)
print("auc_score :",auc_score_Bilstm)

Accuracy : 0.8708159698884259
Precision: 0.8758134490238612
Recall   : 0.8652558264130726
F1 Score : 0.8705026276782105
auc_score : 0.870836224053811


In [63]:
performance("BILSTM",0.87,0.87,0.86,0.87,0.87)

In [71]:
baseline_performance

{'MODEL': ['ANN', 'RNN', 'LSTM', 'GRU', 'BILSTM'],
 'ACCURACY': [0.87, 0.51, 0.87, 0.87, 0.87],
 'PRECISION': [0.85, 0.54, 0.85, 0.87, 0.87],
 'RECALL': [0.91, 0.24, 0.89, 0.89, 0.86],
 'F1 SCORE': [0.88, 0.33, 0.87, 0.88, 0.87],
 'AUC': [0.87, 0.51, 0.87, 0.87, 0.87]}

In [70]:
Bilstm_model.save(r"../model/base_bilstm.keras")

In [65]:
df = pd.DataFrame(baseline_performance)
df.to_csv(r"../data/performance/base_model_performance.csv",index=False)